// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Pokemon pokemon
//
// swagger:model Pokemon
type Pokemon struct {

	// description
	Description string `json:"description,omitempty"`

	// habitat
	Habitat string `json:"habitat,omitempty"`

	// is legendary
	// Required: true
	IsLegendary *bool `json:"isLegendary"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this pokemon
func (m *Pokemon) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIsLegendary(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Pokemon) validateIsLegendary(formats strfmt.Registry) error {

	if err := validate.Required("isLegendary", "body", m.IsLegendary); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this pokemon based on context it is used
func (m *Pokemon) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pokemon) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pokemon) UnmarshalBinary(b []byte) error {
	var res Pokemon
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
