// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPokemonNameParams creates a new GetPokemonNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPokemonNameParams() *GetPokemonNameParams {
	return &GetPokemonNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPokemonNameParamsWithTimeout creates a new GetPokemonNameParams object
// with the ability to set a timeout on a request.
func NewGetPokemonNameParamsWithTimeout(timeout time.Duration) *GetPokemonNameParams {
	return &GetPokemonNameParams{
		timeout: timeout,
	}
}

// NewGetPokemonNameParamsWithContext creates a new GetPokemonNameParams object
// with the ability to set a context for a request.
func NewGetPokemonNameParamsWithContext(ctx context.Context) *GetPokemonNameParams {
	return &GetPokemonNameParams{
		Context: ctx,
	}
}

// NewGetPokemonNameParamsWithHTTPClient creates a new GetPokemonNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPokemonNameParamsWithHTTPClient(client *http.Client) *GetPokemonNameParams {
	return &GetPokemonNameParams{
		HTTPClient: client,
	}
}

/* GetPokemonNameParams contains all the parameters to send to the API endpoint
   for the get pokemon name operation.

   Typically these are written to a http.Request.
*/
type GetPokemonNameParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get pokemon name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPokemonNameParams) WithDefaults() *GetPokemonNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get pokemon name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPokemonNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get pokemon name params
func (o *GetPokemonNameParams) WithTimeout(timeout time.Duration) *GetPokemonNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pokemon name params
func (o *GetPokemonNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pokemon name params
func (o *GetPokemonNameParams) WithContext(ctx context.Context) *GetPokemonNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pokemon name params
func (o *GetPokemonNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pokemon name params
func (o *GetPokemonNameParams) WithHTTPClient(client *http.Client) *GetPokemonNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pokemon name params
func (o *GetPokemonNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get pokemon name params
func (o *GetPokemonNameParams) WithName(name string) *GetPokemonNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get pokemon name params
func (o *GetPokemonNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetPokemonNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
