// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmalad3/pokemon/internal/app/pokedex/models"
)

// GetPokemonTranslatedNameReader is a Reader for the GetPokemonTranslatedName structure.
type GetPokemonTranslatedNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPokemonTranslatedNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPokemonTranslatedNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetPokemonTranslatedNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPokemonTranslatedNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPokemonTranslatedNameOK creates a GetPokemonTranslatedNameOK with default headers values
func NewGetPokemonTranslatedNameOK() *GetPokemonTranslatedNameOK {
	return &GetPokemonTranslatedNameOK{}
}

/* GetPokemonTranslatedNameOK describes a response with status code 200, with default header values.

OK
*/
type GetPokemonTranslatedNameOK struct {
	Payload *models.Pokemon
}

func (o *GetPokemonTranslatedNameOK) Error() string {
	return fmt.Sprintf("[GET /pokemon/translated/{name}][%d] getPokemonTranslatedNameOK  %+v", 200, o.Payload)
}
func (o *GetPokemonTranslatedNameOK) GetPayload() *models.Pokemon {
	return o.Payload
}

func (o *GetPokemonTranslatedNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Pokemon)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPokemonTranslatedNameNotFound creates a GetPokemonTranslatedNameNotFound with default headers values
func NewGetPokemonTranslatedNameNotFound() *GetPokemonTranslatedNameNotFound {
	return &GetPokemonTranslatedNameNotFound{}
}

/* GetPokemonTranslatedNameNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetPokemonTranslatedNameNotFound struct {
}

func (o *GetPokemonTranslatedNameNotFound) Error() string {
	return fmt.Sprintf("[GET /pokemon/translated/{name}][%d] getPokemonTranslatedNameNotFound ", 404)
}

func (o *GetPokemonTranslatedNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPokemonTranslatedNameInternalServerError creates a GetPokemonTranslatedNameInternalServerError with default headers values
func NewGetPokemonTranslatedNameInternalServerError() *GetPokemonTranslatedNameInternalServerError {
	return &GetPokemonTranslatedNameInternalServerError{}
}

/* GetPokemonTranslatedNameInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type GetPokemonTranslatedNameInternalServerError struct {
}

func (o *GetPokemonTranslatedNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /pokemon/translated/{name}][%d] getPokemonTranslatedNameInternalServerError ", 500)
}

func (o *GetPokemonTranslatedNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
