// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetPokemonName(params *GetPokemonNameParams, opts ...ClientOption) (*GetPokemonNameOK, error)

	GetPokemonTranslatedName(params *GetPokemonTranslatedNameParams, opts ...ClientOption) (*GetPokemonTranslatedNameOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetPokemonName returns a pokemon by name
*/
func (a *Client) GetPokemonName(params *GetPokemonNameParams, opts ...ClientOption) (*GetPokemonNameOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPokemonNameParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetPokemonName",
		Method:             "GET",
		PathPattern:        "/pokemon/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPokemonNameReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPokemonNameOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPokemonName: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetPokemonTranslatedName returns a pokemon by name with a translated description
*/
func (a *Client) GetPokemonTranslatedName(params *GetPokemonTranslatedNameParams, opts ...ClientOption) (*GetPokemonTranslatedNameOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPokemonTranslatedNameParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetPokemonTranslatedName",
		Method:             "GET",
		PathPattern:        "/pokemon/translated/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPokemonTranslatedNameReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPokemonTranslatedNameOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPokemonTranslatedName: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
